services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: cafeteria
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: senha123
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cafeteria-net

  backend:
    build: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/cafeteria?sslmode=disable
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: senha123
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
    networks:
      - cafeteria-net

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - cafeteria-net

volumes:
  db_data:

networks:
  cafeteria-net:
